### ISSUE TITLE
vSphere `cloud_provider` mandatory settings without effect when using node templates

### ISSUE THREAD

**Issue by timobartels** [rancher/terraform-provider-rancher2-archive#97]
tested with [version](https://github.com/rancher/terraform-provider-rancher2/releases/tag/v0.2.0-rc5) 0.2.0-rc5

I have a `node_template` configured to manage K8s cluster in our on-prem vSphere. All information on where to place the cluster and which credentials to be used are stored in the `node template` and associated `cloud credentials`.
But in order to successfully create a K8s cluster via terraform rancher2 provider, I still need to provide the structure like below (even though all values are set to "bla", which are indeed ignored by the provider due to existence of a node template)
```
cloud_provider {
  name = "vsphere"
  vsphere_cloud_provider {
    virtual center {
      datacenters = "bla"
      name = "bla"
      password = "bla"
      user = "bla"
    }
    workspace {
      datacenter = "bla"
      folder = "bla"
      server = "bla"
      default_datastore = "bla"
    }
  }
}
```

Above config works, but it is not desirable to set some dummy values. 
If I completely omit the `vsphere_cloud_provider` section (or the `virtual_center` / `workspace` sections within), the cluster build fails with following error message in Rancher UI:
 
`Can not find RKE state file: open /var/lib/rancher/management-state/rke/rke-796758717/cluster.rkestate: no such file or directory`

I think the desired functionality should be that, if an existing node template is found, the entire `vsphere_cloud_provider` section should not be mandatory but optiional (to override whatever is configured in the node template).

**Comment by rawmind0** [comment]
Hi @timobartels,

`node_template` and rke `cloud_provider` are 2 separate thinks:
- `node_template` is just a template configuration to deploy vm's on a infrastructure using distinct drivers, vsphere in your case. Here the configuration is just to deploy vm's nothing to do with what vm's are running on top.
- rke `cloud_provider` is a rke configuration to integrate k8s cluster with your cloud provider, in your case [`vsphere_cloud_provider`] (https://vmware.github.io/vsphere-storage-for-kubernetes/documentation/) indeed for vsphere storage integration with k8s.

You could use `node_template` with vsphere driver and not use rke `cloud_provider` (if you don't need vpshere integration on k8s deployments) and the reverse, deploy your vm's by yourself on vsphere and configure rke `cloud_provider` to integrate vsphere storage on your k8s deployments.

If you want to use [rke `vsphere_cloud_provider` integration](https://rancher.com/docs/rke/latest/en/config-options/cloud-providers/vsphere/),  `virtual_center` and `workspace` are required, because they are needed to manage vsphere volumes for k8s deployments. If you setup these with dummy values, they are not ignored by the provider due to existence of a node template, rke doesn't know anything about node template (just vm's ip). RKE cluster deployment is working due to not using them , but if at some point, you'd need a k8s volume in your k8s deployments, it will fail due to using dummy values. 

Instead omit `vsphere_cloud_provider` section, have you tried to deploy cluster removing completely `cloud_provider` section, if you don't need k8s deployments storage integration?? If you already tried, have you got same error message??

**Comment by rawmind0** [comment]
Due to rancher2 terraform provider is already officially supported by Hashicorp, this repo is going to be archived.

Please consider reopen issue on https://github.com/terraform-providers/terraform-provider-rancher2 if needed.
